export const OFFICIAL_FEEDS = [
  {
    name: 'Minecraft 麥塊',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=Minecraft+OR+當個創世神&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/5/51/Minecraft_cover.png',
    description: '全球最受歡迎的沙盒遊戲，方塊世界的新鮮事。',
  },
  {
    name: '英雄聯盟 League of Legends',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=英雄聯盟+OR+League+of+Legends&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/d/d8/League_of_Legends_2019_vector.svg',
    description: 'LOL 官方更新、電競賽事與英雄調整情報。',
  },
  {
    name: '特戰英豪 VALORANT',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=特戰英豪+OR+VALORANT&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Valorant_logo_-_pink_color_version.svg',
    description: 'Riot Games 5v5 戰術射擊遊戲情報。',
  },
  {
    name: 'Apex 英雄 Apex Legends',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=Apex+Legends+OR+Apex英雄&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/d/d0/Apex_legends_cover.jpg',
    description: '捍衛者集合！Apex 英雄最新賽季與活動。',
  },
  {
    name: '原神 Genshin Impact',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=原神+OR+Genshin+Impact&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/5/5d/Genshin_Impact_logo.svg',
    description: '提瓦特大陸的冒險指南與官方前瞻。',
  },
  {
    name: '崩壞：星穹鐵道',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=崩壞：星穹鐵道+OR+Honkai+Star+Rail&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/4/4b/Honkai_Star_Rail.png',
    description: '願此行，終抵群星！星穹鐵道最新活動。',
  },
  {
    name: '絕地求生 PUBG',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=絕地求生+OR+PUBG&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/1/1a/PlayerUnknown%27s_Battlegrounds_cover.jpg',
    description: '大吉大利，今晚吃雞！PUBG 最新更新。',
  },
  {
    name: '絕對武力 CS2',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=CS2+OR+Counter-Strike+2&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/f/f2/CS2_Cover_Art.jpg',
    description: 'CS2 賽事、更新與社群情報。',
  },
  {
    name: '鬥陣特攻 Overwatch 2',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=鬥陣特攻2+OR+Overwatch+2&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/9/90/Overwatch_2_logo.svg',
    description: '捍衛者再臨，鬥陣特攻最新消息。',
  },
  {
    name: '魔獸世界 World of Warcraft',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=魔獸世界+OR+World+of+Warcraft&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/9/91/WoW_Box_Art1.jpg',
    description: '艾澤拉斯的最新史詩冒險。',
  },
  {
    name: '暗黑破壞神 Diablo IV',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=暗黑破壞神4+OR+Diablo+4&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/c/cb/Diablo_IV_cover_art.png',
    description: '聖休亞瑞的最新賽季情報。',
  },
  {
    name: '聯盟戰棋 TFT',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=聯盟戰棋+OR+Teamfight+Tactics&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Teamfight_Tactics_logo.png',
    description: '最新棋組更新與陣容討論。',
  },
  {
    name: '決勝時刻 Call of Duty',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=決勝時刻+OR+Call+of+Duty&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Call_of_Duty_logo.svg',
    description: '現代戰爭、黑色行動與現代戰域情報。',
  },
  {
    name: '要塞英雄 Fortnite',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=要塞英雄+OR+Fortnite&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/3/31/Epic_Games_logo.svg',
    description: 'Fortnite 最新賽季與聯動合作。',
  },
  {
    name: '俠盜獵車手 GTA 5',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=GTA5+OR+俠盜獵車手&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/a/a5/Grand_Theft_Auto_V.png',
    description: '洛聖都的日常與線上模式更新。',
  },
  {
    name: '艾爾登法環 Elden Ring',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=艾爾登法環+OR+Elden+Ring&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/b/b9/Elden_Ring_Box_art.jpg',
    description: '褪色者們的交界地探索與 DLC 資訊。',
  },
  {
    name: '魔物獵人 Monster Hunter',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=魔物獵人+OR+Monster+Hunter&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Monster_Hunter_World_cover_art.jpg',
    description: '全系列狩獵情報與新裝備。',
  },
  {
    name: 'Final Fantasy XIV',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=FF14+OR+Final+Fantasy+XIV&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/1/18/Final_Fantasy_XIV_-_A_Realm_Reborn_box_art.jpg',
    description: '光之戰士的艾歐澤亞冒險與改版。',
  },
  {
    name: '薩爾達傳說 曠野/王國',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=薩爾達傳說+OR+Zelda&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/f/f6/The_Legend_of_Zelda_Tears_of_the_Kingdom_cover.jpg',
    description: '海拉魯大陸的探索與神廟攻略。',
  },
  {
    name: '斯普拉遁 Splatoon 3',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=斯普拉遁3+OR+Splatoon+3&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Splatoon_3_Switch_Box_Art.png',
    description: '漆彈大作戰祭典與賽季資訊。',
  },
  {
    name: '集合啦！動物森友會',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=動物森友會+OR+Animal+Crossing&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/1/1f/Animal_Crossing_New_Horizons.jpg',
    description: '無人島的悠閒生活與島民分享。',
  },
  {
    name: '瑪利歐賽車 Mario Kart',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=瑪利歐賽車+OR+Mario+Kart&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/b/b5/MarioKart8Boxart.jpg',
    description: '飆速對決與賽道更新。',
  },
  {
    name: '任天堂明星大亂鬥',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=任天堂明星大亂鬥+OR+Smash+Bros&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/4/44/Super_Smash_Bros._Ultimate.jpg',
    description: '大亂鬥賽事與操作技巧。',
  },
  {
    name: '寶可夢 Pokemon',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=寶可夢+OR+Pokemon&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/9/98/International_Pok%C3%A9mon_logo.svg',
    description: '寶可夢本傳、GO與卡牌情報。',
  },
  {
    name: '碧血狂殺 Red Dead Redemption',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=碧血狂殺2+OR+Red+Dead+Redemption&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg',
    description: '荒野大鏢客的美國西部時光。',
  },
  {
    name: '巫師 The Witcher',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=巫師3+OR+The+Witcher&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Witcher_3_cover_art.jpg',
    description: '傑洛特的奇幻冒險。',
  },
  {
    name: '電馭叛客 Cyberpunk 2077',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=電馭叛客+OR+Cyberpunk+2077&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Cyberpunk_2077_box_art.jpg',
    description: '夜城生存法則與幻影自由。',
  },
  {
    name: 'Roblox 機器磚塊',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=Roblox+OR+機器磚塊&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/3/3a/Roblox_player_icon_black.svg',
    description: '發揮創意的遊戲創作平台。',
  },
  {
    name: 'Terraria 泰拉瑞亞',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=Terraria+OR+泰拉瑞亞&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/8/81/Terraria_game_cover.png',
    description: '2D 沙盒生存冒險。',
  },
  {
    name: '星露谷物語 Stardew Valley',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=星露谷物語+OR+Stardew+Valley&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/f/fd/Stardew_Valley_cover_art.jpg',
    description: '輕鬆悠閒的農場經營模擬。',
  },
  {
    name: '黎明死線 Dead by Daylight',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=黎明死線+OR+Dead+by+Daylight&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/c/cc/Dead_By_Daylight_Cover.jpg',
    description: '1對4非對稱恐怖生存競技。',
  },
  {
    name: '虹彩六號 Rainbow Six',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=虹彩六號+OR+Rainbow+Six+Siege&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/4/47/Tom_Clancy%27s_Rainbow_Six_Siege_cover_art.jpg',
    description: '戰術攻防與探員情報。',
  },
  {
    name: '天命2 Destiny 2',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=天命2+OR+Destiny+2&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/0/05/Destiny_2_%28artwork%29.jpg',
    description: '科幻掠寶射擊遊戲最新改版。',
  },
  {
    name: 'Warframe 戰甲神兵',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=Warframe+OR+戰甲神兵&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/3/30/Warframe_Cover_Art.jpg',
    description: '星際忍者的刷寶之旅。',
  },
  {
    name: '流亡黯道 Path of Exile',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=流亡黯道+OR+Path+of+Exile&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/0/08/Path_of_Exile_Logo.png',
    description: '硬核 ARPG 賽季開荒與流派。',
  },
  {
    name: '快打旋風 Street Fighter',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=快打旋風6+OR+Street+Fighter&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/8/87/Street_Fighter_6_box_art.jpg',
    description: '格鬥遊戲最高殿堂賽事情報。',
  },
  {
    name: '鐵拳 Tekken',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=鐵拳8+OR+Tekken&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/5/53/Tekken_8_cover_art.jpg',
    description: '鐵拳系列最新比賽與角色。',
  },
  {
    name: '柏德之門 Baldur\'s Gate',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=柏德之門3+OR+Baldurs+Gate&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Baldurs_Gate_3_Cover_Art.png',
    description: 'D&D 規則史詩 RPG 討論。',
  },
  {
    name: '絕地戰兵 Helldivers',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=絕地戰兵2+OR+Helldivers+2&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/9/90/Helldivers_2_cover_art.jpg',
    description: '為了超級地球！民主的擴張與更新。',
  },
  {
    name: '幻獸帕魯 Palworld',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=幻獸帕魯+OR+Palworld&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/5/54/Palworld_cover_art.jpg',
    description: '捕捉帕魯與建造基地的生活。',
  },
  {
    name: '霧鎖王國 Enshrouded',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=霧鎖王國+OR+Enshrouded&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/8/87/Enshrouded_cover.jpg',
    description: '迷霧生存與建築分享。',
  },
  {
    name: '方舟 ARK',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=方舟生存+OR+ARK+Survival&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/8/80/ARK_Survival_Evolved_Cover.jpg',
    description: '恐龍島生存法則。',
  },
  {
    name: 'Rust 腐蝕',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=Rust+遊戲&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/7/73/Rust_video_game_cover_art.jpg',
    description: '硬派生存與掠奪。',
  },
  {
    name: '逃離塔科夫 Escape from Tarkov',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=逃離塔科夫+OR+Tarkov&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/0/08/Escape_from_Tarkov.png',
    description: '硬核射擊搜刮體驗。',
  },
  {
    name: '碧藍幻想 Granblue Fantasy',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=碧藍幻想+OR+Granblue+Fantasy&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/1/1a/Granblue_Fantasy_Relink_cover_art.jpg',
    description: '騎空士的冒險與連線。',
  },
  {
    name: '鳴潮 Wuthering Waves',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=鳴潮+OR+Wuthering+Waves&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/7/77/Wuthering_Waves_Cover_Art.png',
    description: '動作角色扮演與庫洛情報。',
  },
  {
    name: '絕區零 Zenless Zone Zero',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=絕區零+OR+Zenless+Zone+Zero&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/b/b3/Zenless_Zone_Zero.png',
    description: '米哈遊全新都市動作遊戲。',
  },
  {
    name: 'RO 仙境傳說',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=仙境傳說+OR+Ragnarok&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/5/5e/Ragnarok_Online_Coverart.png',
    description: '經典 MMORPG 情報與回憶。',
  },
  {
    name: '跑跑卡丁車 KartRider',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=跑跑卡丁車+OR+KartRider&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/en/5/54/KartRider_Rush%2B_app_icon.png',
    description: '全民競速賽事與飄移技巧。',
  },
  {
    name: 'Steam 綜合遊戲情報',
    category: '遊戲',
    url: 'https://news.google.com/rss/search?q=Steam+Games&hl=zh-TW&gl=TW&ceid=TW:zh-Hant',
    logo_url: 'https://upload.wikimedia.org/wikipedia/commons/8/83/Steam_icon_logo.svg',
    description: 'Steam 平台特賣、新品與官方資訊。',
  },
  {
    name: '巴哈姆特遊戲情報',
    category: '資訊',
    url: 'https://gnn.gamer.com.tw/rss.xml',
    logo_url: 'https://i.imgur.com/G5Z5oQ9.png',
    description: '自動同步巴哈姆特 GNN 新聞，提供最新的遊戲、動漫情報。',
  },
  {
    name: '科技新報 TechNews',
    category: '科技',
    url: 'https://technews.tw/feed/',
    logo_url: 'https://i.imgur.com/Uo2w9XG.png',
    description: '最新的科技、Web 與軟體產業資訊分享。',
  }
];
